//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Aggregation) DeepCopyInto(out *Aggregation) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(AggregationFilter)
		**out = **in
	}
	if in.Percentile != nil {
		in, out := &in.Percentile, &out.Percentile
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Aggregation.
func (in *Aggregation) DeepCopy() *Aggregation {
	if in == nil {
		return nil
	}
	out := new(Aggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregationFilter) DeepCopyInto(out *AggregationFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregationFilter.
func (in *AggregationFilter) DeepCopy() *AggregationFilter {
	if in == nil {
		return nil
	}
	out := new(AggregationFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregationVisibility) DeepCopyInto(out *AggregationVisibility) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregationVisibility.
func (in *AggregationVisibility) DeepCopy() *AggregationVisibility {
	if in == nil {
		return nil
	}
	out := new(AggregationVisibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnection) DeepCopyInto(out *ClusterConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnection.
func (in *ClusterConnection) DeepCopy() *ClusterConnection {
	if in == nil {
		return nil
	}
	out := new(ClusterConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionList) DeepCopyInto(out *ClusterConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionList.
func (in *ClusterConnectionList) DeepCopy() *ClusterConnectionList {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionSpec) DeepCopyInto(out *ClusterConnectionSpec) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Monitoring = in.Monitoring
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionSpec.
func (in *ClusterConnectionSpec) DeepCopy() *ClusterConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionStatus) DeepCopyInto(out *ClusterConnectionStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.CollectorStatus != nil {
		in, out := &in.CollectorStatus, &out.CollectorStatus
		*out = new(CollectorAgentStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionStatus.
func (in *ClusterConnectionStatus) DeepCopy() *ClusterConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionConfig) DeepCopyInto(out *CollectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionConfig.
func (in *CollectionConfig) DeepCopy() *CollectionConfig {
	if in == nil {
		return nil
	}
	out := new(CollectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorAgentStatus) DeepCopyInto(out *CollectorAgentStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorAgentStatus.
func (in *CollectorAgentStatus) DeepCopy() *CollectorAgentStatus {
	if in == nil {
		return nil
	}
	out := new(CollectorAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputedField) DeepCopyInto(out *ComputedField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputedField.
func (in *ComputedField) DeepCopy() *ComputedField {
	if in == nil {
		return nil
	}
	out := new(ComputedField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsReference) DeepCopyInto(out *CredentialsReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsReference.
func (in *CredentialsReference) DeepCopy() *CredentialsReference {
	if in == nil {
		return nil
	}
	out := new(CredentialsReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldExtraction) DeepCopyInto(out *FieldExtraction) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldExtraction.
func (in *FieldExtraction) DeepCopy() *FieldExtraction {
	if in == nil {
		return nil
	}
	out := new(FieldExtraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldValidationStatus) DeepCopyInto(out *FieldValidationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldValidationStatus.
func (in *FieldValidationStatus) DeepCopy() *FieldValidationStatus {
	if in == nil {
		return nil
	}
	out := new(FieldValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceList) DeepCopyInto(out *MetricSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceList.
func (in *MetricSourceList) DeepCopy() *MetricSourceList {
	if in == nil {
		return nil
	}
	out := new(MetricSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceRBAC) DeepCopyInto(out *MetricSourceRBAC) {
	*out = *in
	if in.FilterableFields != nil {
		in, out := &in.FilterableFields, &out.FilterableFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceRBAC.
func (in *MetricSourceRBAC) DeepCopy() *MetricSourceRBAC {
	if in == nil {
		return nil
	}
	out := new(MetricSourceRBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceSpec) DeepCopyInto(out *MetricSourceSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FieldExtraction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Computed != nil {
		in, out := &in.Computed, &out.Computed
		*out = make([]ComputedField, len(*in))
		copy(*out, *in)
	}
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = make([]Aggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Collection = in.Collection
	in.RBAC.DeepCopyInto(&out.RBAC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceSpec.
func (in *MetricSourceSpec) DeepCopy() *MetricSourceSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceStatus) DeepCopyInto(out *MetricSourceStatus) {
	*out = *in
	if in.LastCollectionTime != nil {
		in, out := &in.LastCollectionTime, &out.LastCollectionTime
		*out = (*in).DeepCopy()
	}
	if in.FieldValidation != nil {
		in, out := &in.FieldValidation, &out.FieldValidation
		*out = make([]FieldValidationStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceStatus.
func (in *MetricSourceStatus) DeepCopy() *MetricSourceStatus {
	if in == nil {
		return nil
	}
	out := new(MetricSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSourceTarget) DeepCopyInto(out *MetricSourceTarget) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(NamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSourceTarget.
func (in *MetricSourceTarget) DeepCopy() *MetricSourceTarget {
	if in == nil {
		return nil
	}
	out := new(MetricSourceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorAccessPolicy) DeepCopyInto(out *MonitorAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorAccessPolicy.
func (in *MonitorAccessPolicy) DeepCopy() *MonitorAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(MonitorAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitorAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorAccessPolicyList) DeepCopyInto(out *MonitorAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitorAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorAccessPolicyList.
func (in *MonitorAccessPolicyList) DeepCopy() *MonitorAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(MonitorAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitorAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorAccessPolicySpec) DeepCopyInto(out *MonitorAccessPolicySpec) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
	in.Access.DeepCopyInto(&out.Access)
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(PolicyLifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(PolicyOperations)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorAccessPolicySpec.
func (in *MonitorAccessPolicySpec) DeepCopy() *MonitorAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MonitorAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorAccessPolicyStatus) DeepCopyInto(out *MonitorAccessPolicyStatus) {
	*out = *in
	if in.CustomResourceWarnings != nil {
		in, out := &in.CustomResourceWarnings, &out.CustomResourceWarnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorAccessPolicyStatus.
func (in *MonitorAccessPolicyStatus) DeepCopy() *MonitorAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MonitorAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternFilter) DeepCopyInto(out *PatternFilter) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Denied != nil {
		in, out := &in.Denied, &out.Denied
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternFilter.
func (in *PatternFilter) DeepCopy() *PatternFilter {
	if in == nil {
		return nil
	}
	out := new(PatternFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAccess) DeepCopyInto(out *PolicyAccess) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAccess.
func (in *PolicyAccess) DeepCopy() *PolicyAccess {
	if in == nil {
		return nil
	}
	out := new(PolicyAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAudit) DeepCopyInto(out *PolicyAudit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAudit.
func (in *PolicyAudit) DeepCopy() *PolicyAudit {
	if in == nil {
		return nil
	}
	out := new(PolicyAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyClusterRule) DeepCopyInto(out *PolicyClusterRule) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(PolicyPermissions)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyClusterRule.
func (in *PolicyClusterRule) DeepCopy() *PolicyClusterRule {
	if in == nil {
		return nil
	}
	out := new(PolicyClusterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyClusterSelector) DeepCopyInto(out *PolicyClusterSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyClusterSelector.
func (in *PolicyClusterSelector) DeepCopy() *PolicyClusterSelector {
	if in == nil {
		return nil
	}
	out := new(PolicyClusterSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyClusters) DeepCopyInto(out *PolicyClusters) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyClusterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyClusters.
func (in *PolicyClusters) DeepCopy() *PolicyClusters {
	if in == nil {
		return nil
	}
	out := new(PolicyClusters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyIdentity) DeepCopyInto(out *PolicyIdentity) {
	*out = *in
	in.Subjects.DeepCopyInto(&out.Subjects)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyIdentity.
func (in *PolicyIdentity) DeepCopy() *PolicyIdentity {
	if in == nil {
		return nil
	}
	out := new(PolicyIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLifecycle) DeepCopyInto(out *PolicyLifecycle) {
	*out = *in
	if in.Validity != nil {
		in, out := &in.Validity, &out.Validity
		*out = new(PolicyValidity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLifecycle.
func (in *PolicyLifecycle) DeepCopy() *PolicyLifecycle {
	if in == nil {
		return nil
	}
	out := new(PolicyLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyOperations) DeepCopyInto(out *PolicyOperations) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(PolicyAudit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyOperations.
func (in *PolicyOperations) DeepCopy() *PolicyOperations {
	if in == nil {
		return nil
	}
	out := new(PolicyOperations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPermissions) DeepCopyInto(out *PolicyPermissions) {
	*out = *in
	if in.View != nil {
		in, out := &in.View, &out.View
		*out = new(bool)
		**out = **in
	}
	if in.ViewMetrics != nil {
		in, out := &in.ViewMetrics, &out.ViewMetrics
		*out = new(bool)
		**out = **in
	}
	if in.ViewSensitive != nil {
		in, out := &in.ViewSensitive, &out.ViewSensitive
		*out = new(bool)
		**out = **in
	}
	if in.ViewCosts != nil {
		in, out := &in.ViewCosts, &out.ViewCosts
		*out = new(bool)
		**out = **in
	}
	if in.ViewSecrets != nil {
		in, out := &in.ViewSecrets, &out.ViewSecrets
		*out = new(bool)
		**out = **in
	}
	if in.ViewMetadata != nil {
		in, out := &in.ViewMetadata, &out.ViewMetadata
		*out = new(bool)
		**out = **in
	}
	if in.ViewAuditInfo != nil {
		in, out := &in.ViewAuditInfo, &out.ViewAuditInfo
		*out = new(bool)
		**out = **in
	}
	if in.Edit != nil {
		in, out := &in.Edit, &out.Edit
		*out = new(bool)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(bool)
		**out = **in
	}
	if in.Execute != nil {
		in, out := &in.Execute, &out.Execute
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPermissions.
func (in *PolicyPermissions) DeepCopy() *PolicyPermissions {
	if in == nil {
		return nil
	}
	out := new(PolicyPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyScope) DeepCopyInto(out *PolicyScope) {
	*out = *in
	in.Clusters.DeepCopyInto(&out.Clusters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyScope.
func (in *PolicyScope) DeepCopy() *PolicyScope {
	if in == nil {
		return nil
	}
	out := new(PolicyScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyServiceAccount) DeepCopyInto(out *PolicyServiceAccount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyServiceAccount.
func (in *PolicyServiceAccount) DeepCopy() *PolicyServiceAccount {
	if in == nil {
		return nil
	}
	out := new(PolicyServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySubjects) DeepCopyInto(out *PolicySubjects) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]PolicyServiceAccount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySubjects.
func (in *PolicySubjects) DeepCopy() *PolicySubjects {
	if in == nil {
		return nil
	}
	out := new(PolicySubjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyValidity) DeepCopyInto(out *PolicyValidity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyValidity.
func (in *PolicyValidity) DeepCopy() *PolicyValidity {
	if in == nil {
		return nil
	}
	out := new(PolicyValidity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConnection) DeepCopyInto(out *RegistryConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConnection.
func (in *RegistryConnection) DeepCopy() *RegistryConnection {
	if in == nil {
		return nil
	}
	out := new(RegistryConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConnectionList) DeepCopyInto(out *RegistryConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConnectionList.
func (in *RegistryConnectionList) DeepCopy() *RegistryConnectionList {
	if in == nil {
		return nil
	}
	out := new(RegistryConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConnectionSpec) DeepCopyInto(out *RegistryConnectionSpec) {
	*out = *in
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(CredentialsReference)
		**out = **in
	}
	out.Monitoring = in.Monitoring
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HealthCheckPaths != nil {
		in, out := &in.HealthCheckPaths, &out.HealthCheckPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConnectionSpec.
func (in *RegistryConnectionSpec) DeepCopy() *RegistryConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConnectionStatus) DeepCopyInto(out *RegistryConnectionStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConnectionStatus.
func (in *RegistryConnectionStatus) DeepCopy() *RegistryConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryMonitoringConfig) DeepCopyInto(out *RegistryMonitoringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryMonitoringConfig.
func (in *RegistryMonitoringConfig) DeepCopy() *RegistryMonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryMonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFilter) DeepCopyInto(out *ResourceFilter) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(ResourceFilterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = new(AggregationVisibility)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFilter.
func (in *ResourceFilter) DeepCopy() *ResourceFilter {
	if in == nil {
		return nil
	}
	out := new(ResourceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFilterSpec) DeepCopyInto(out *ResourceFilterSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(PatternFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = new(PatternFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]PatternFilter, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFilterSpec.
func (in *ResourceFilterSpec) DeepCopy() *ResourceFilterSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceFilterSpec)
	in.DeepCopyInto(out)
	return out
}
