// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: collector.proto

package collectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectorMessage is sent from collector agent to hub ingester.
type CollectorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CollectorMessage_Metrics
	//	*CollectorMessage_Health
	//	*CollectorMessage_Register
	Payload       isCollectorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorMessage) Reset() {
	*x = CollectorMessage{}
	mi := &file_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorMessage) ProtoMessage() {}

func (x *CollectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorMessage.ProtoReflect.Descriptor instead.
func (*CollectorMessage) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorMessage) GetPayload() isCollectorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CollectorMessage) GetMetrics() *MetricsBatch {
	if x != nil {
		if x, ok := x.Payload.(*CollectorMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *CollectorMessage) GetHealth() *HealthReport {
	if x != nil {
		if x, ok := x.Payload.(*CollectorMessage_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *CollectorMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*CollectorMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

type isCollectorMessage_Payload interface {
	isCollectorMessage_Payload()
}

type CollectorMessage_Metrics struct {
	Metrics *MetricsBatch `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type CollectorMessage_Health struct {
	Health *HealthReport `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

type CollectorMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

func (*CollectorMessage_Metrics) isCollectorMessage_Payload() {}

func (*CollectorMessage_Health) isCollectorMessage_Payload() {}

func (*CollectorMessage_Register) isCollectorMessage_Payload() {}

// IngesterMessage is sent from hub ingester to collector agent.
type IngesterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IngesterMessage_Config
	//	*IngesterMessage_Ack
	Payload       isIngesterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngesterMessage) Reset() {
	*x = IngesterMessage{}
	mi := &file_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngesterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngesterMessage) ProtoMessage() {}

func (x *IngesterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngesterMessage.ProtoReflect.Descriptor instead.
func (*IngesterMessage) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{1}
}

func (x *IngesterMessage) GetPayload() isIngesterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngesterMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*IngesterMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *IngesterMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*IngesterMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isIngesterMessage_Payload interface {
	isIngesterMessage_Payload()
}

type IngesterMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type IngesterMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*IngesterMessage_Config) isIngesterMessage_Payload() {}

func (*IngesterMessage_Ack) isIngesterMessage_Payload() {}

// RegisterRequest is the first message a collector sends to identify itself.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// MetricsBatch contains collected metrics from one collection cycle.
type MetricsBatch struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClusterName string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	BatchId     string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	CollectedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	// Core cluster metrics
	ClusterMetrics *ClusterMetrics `protobuf:"bytes,4,opt,name=cluster_metrics,json=clusterMetrics,proto3" json:"cluster_metrics,omitempty"`
	NodeMetrics    []*NodeMetrics  `protobuf:"bytes,5,rep,name=node_metrics,json=nodeMetrics,proto3" json:"node_metrics,omitempty"`
	// Custom resource collections from MetricSources
	CustomResources []*CustomResourceBatch `protobuf:"bytes,6,rep,name=custom_resources,json=customResources,proto3" json:"custom_resources,omitempty"`
	// Operator data
	Operators        []*OperatorInfo        `protobuf:"bytes,7,rep,name=operators,proto3" json:"operators,omitempty"`
	ClusterOperators []*ClusterOperatorInfo `protobuf:"bytes,8,rep,name=cluster_operators,json=clusterOperators,proto3" json:"cluster_operators,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsBatch) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *MetricsBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *MetricsBatch) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *MetricsBatch) GetClusterMetrics() *ClusterMetrics {
	if x != nil {
		return x.ClusterMetrics
	}
	return nil
}

func (x *MetricsBatch) GetNodeMetrics() []*NodeMetrics {
	if x != nil {
		return x.NodeMetrics
	}
	return nil
}

func (x *MetricsBatch) GetCustomResources() []*CustomResourceBatch {
	if x != nil {
		return x.CustomResources
	}
	return nil
}

func (x *MetricsBatch) GetOperators() []*OperatorInfo {
	if x != nil {
		return x.Operators
	}
	return nil
}

func (x *MetricsBatch) GetClusterOperators() []*ClusterOperatorInfo {
	if x != nil {
		return x.ClusterOperators
	}
	return nil
}

// ClusterMetrics mirrors pkg/types.ClusterMetrics in protobuf form.
type ClusterMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nodes          int32                  `protobuf:"varint,1,opt,name=nodes,proto3" json:"nodes,omitempty"`
	NodesReady     int32                  `protobuf:"varint,2,opt,name=nodes_ready,json=nodesReady,proto3" json:"nodes_ready,omitempty"`
	Namespaces     int32                  `protobuf:"varint,4,opt,name=namespaces,proto3" json:"namespaces,omitempty"`
	NamespaceList  []string               `protobuf:"bytes,5,rep,name=namespace_list,json=namespaceList,proto3" json:"namespace_list,omitempty"`
	Pods           int32                  `protobuf:"varint,6,opt,name=pods,proto3" json:"pods,omitempty"`
	PodsRunning    int32                  `protobuf:"varint,7,opt,name=pods_running,json=podsRunning,proto3" json:"pods_running,omitempty"`
	CpuCapacity    float64                `protobuf:"fixed64,10,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	MemoryCapacity int64                  `protobuf:"varint,14,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	Deployments    int32                  `protobuf:"varint,22,opt,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterMetrics) Reset() {
	*x = ClusterMetrics{}
	mi := &file_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetrics) ProtoMessage() {}

func (x *ClusterMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetrics.ProtoReflect.Descriptor instead.
func (*ClusterMetrics) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterMetrics) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ClusterMetrics) GetNodesReady() int32 {
	if x != nil {
		return x.NodesReady
	}
	return 0
}

func (x *ClusterMetrics) GetNamespaces() int32 {
	if x != nil {
		return x.Namespaces
	}
	return 0
}

func (x *ClusterMetrics) GetNamespaceList() []string {
	if x != nil {
		return x.NamespaceList
	}
	return nil
}

func (x *ClusterMetrics) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *ClusterMetrics) GetPodsRunning() int32 {
	if x != nil {
		return x.PodsRunning
	}
	return 0
}

func (x *ClusterMetrics) GetCpuCapacity() float64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *ClusterMetrics) GetMemoryCapacity() int64 {
	if x != nil {
		return x.MemoryCapacity
	}
	return 0
}

func (x *ClusterMetrics) GetDeployments() int32 {
	if x != nil {
		return x.Deployments
	}
	return 0
}

// NodeMetrics mirrors pkg/types.NodeMetrics in protobuf form.
type NodeMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Roles              []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	CpuCapacity        float64                `protobuf:"fixed64,10,opt,name=cpu_capacity,json=cpuCapacity,proto3" json:"cpu_capacity,omitempty"`
	MemoryCapacity     int64                  `protobuf:"varint,11,opt,name=memory_capacity,json=memoryCapacity,proto3" json:"memory_capacity,omitempty"`
	StorageCapacity    int64                  `protobuf:"varint,12,opt,name=storage_capacity,json=storageCapacity,proto3" json:"storage_capacity,omitempty"`
	PodsCapacity       int32                  `protobuf:"varint,13,opt,name=pods_capacity,json=podsCapacity,proto3" json:"pods_capacity,omitempty"`
	CpuAllocatable     float64                `protobuf:"fixed64,14,opt,name=cpu_allocatable,json=cpuAllocatable,proto3" json:"cpu_allocatable,omitempty"`
	MemoryAllocatable  int64                  `protobuf:"varint,15,opt,name=memory_allocatable,json=memoryAllocatable,proto3" json:"memory_allocatable,omitempty"`
	StorageAllocatable int64                  `protobuf:"varint,16,opt,name=storage_allocatable,json=storageAllocatable,proto3" json:"storage_allocatable,omitempty"`
	PodsAllocatable    int32                  `protobuf:"varint,17,opt,name=pods_allocatable,json=podsAllocatable,proto3" json:"pods_allocatable,omitempty"`
	CpuRequested       float64                `protobuf:"fixed64,18,opt,name=cpu_requested,json=cpuRequested,proto3" json:"cpu_requested,omitempty"`
	MemoryRequested    int64                  `protobuf:"varint,19,opt,name=memory_requested,json=memoryRequested,proto3" json:"memory_requested,omitempty"`
	CpuUsagePercent    float64                `protobuf:"fixed64,20,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent float64                `protobuf:"fixed64,21,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	PodsRunning        int32                  `protobuf:"varint,22,opt,name=pods_running,json=podsRunning,proto3" json:"pods_running,omitempty"`
	PodsPending        int32                  `protobuf:"varint,23,opt,name=pods_pending,json=podsPending,proto3" json:"pods_pending,omitempty"`
	PodsFailed         int32                  `protobuf:"varint,24,opt,name=pods_failed,json=podsFailed,proto3" json:"pods_failed,omitempty"`
	PodsSucceeded      int32                  `protobuf:"varint,25,opt,name=pods_succeeded,json=podsSucceeded,proto3" json:"pods_succeeded,omitempty"`
	PodsTotal          int32                  `protobuf:"varint,26,opt,name=pods_total,json=podsTotal,proto3" json:"pods_total,omitempty"`
	KernelVersion      string                 `protobuf:"bytes,30,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	OsImage            string                 `protobuf:"bytes,31,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	ContainerRuntime   string                 `protobuf:"bytes,32,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`
	KubeletVersion     string                 `protobuf:"bytes,33,opt,name=kubelet_version,json=kubeletVersion,proto3" json:"kubelet_version,omitempty"`
	Architecture       string                 `protobuf:"bytes,34,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,35,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InternalIp         string                 `protobuf:"bytes,36,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	Hostname           string                 `protobuf:"bytes,37,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{5}
}

func (x *NodeMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeMetrics) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *NodeMetrics) GetCpuCapacity() float64 {
	if x != nil {
		return x.CpuCapacity
	}
	return 0
}

func (x *NodeMetrics) GetMemoryCapacity() int64 {
	if x != nil {
		return x.MemoryCapacity
	}
	return 0
}

func (x *NodeMetrics) GetStorageCapacity() int64 {
	if x != nil {
		return x.StorageCapacity
	}
	return 0
}

func (x *NodeMetrics) GetPodsCapacity() int32 {
	if x != nil {
		return x.PodsCapacity
	}
	return 0
}

func (x *NodeMetrics) GetCpuAllocatable() float64 {
	if x != nil {
		return x.CpuAllocatable
	}
	return 0
}

func (x *NodeMetrics) GetMemoryAllocatable() int64 {
	if x != nil {
		return x.MemoryAllocatable
	}
	return 0
}

func (x *NodeMetrics) GetStorageAllocatable() int64 {
	if x != nil {
		return x.StorageAllocatable
	}
	return 0
}

func (x *NodeMetrics) GetPodsAllocatable() int32 {
	if x != nil {
		return x.PodsAllocatable
	}
	return 0
}

func (x *NodeMetrics) GetCpuRequested() float64 {
	if x != nil {
		return x.CpuRequested
	}
	return 0
}

func (x *NodeMetrics) GetMemoryRequested() int64 {
	if x != nil {
		return x.MemoryRequested
	}
	return 0
}

func (x *NodeMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *NodeMetrics) GetPodsRunning() int32 {
	if x != nil {
		return x.PodsRunning
	}
	return 0
}

func (x *NodeMetrics) GetPodsPending() int32 {
	if x != nil {
		return x.PodsPending
	}
	return 0
}

func (x *NodeMetrics) GetPodsFailed() int32 {
	if x != nil {
		return x.PodsFailed
	}
	return 0
}

func (x *NodeMetrics) GetPodsSucceeded() int32 {
	if x != nil {
		return x.PodsSucceeded
	}
	return 0
}

func (x *NodeMetrics) GetPodsTotal() int32 {
	if x != nil {
		return x.PodsTotal
	}
	return 0
}

func (x *NodeMetrics) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *NodeMetrics) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *NodeMetrics) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *NodeMetrics) GetKubeletVersion() string {
	if x != nil {
		return x.KubeletVersion
	}
	return ""
}

func (x *NodeMetrics) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *NodeMetrics) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeMetrics) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *NodeMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// CustomResourceBatch holds collected resources for one MetricSource.
type CustomResourceBatch struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	SourceId          string                     `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ResourceCount     int32                      `protobuf:"varint,2,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	Truncated         bool                       `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	DurationMs        int64                      `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Resources         []*CustomCollectedResource `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	AggregationValues map[string]float64         `protobuf:"bytes,6,rep,name=aggregation_values,json=aggregationValues,proto3" json:"aggregation_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomResourceBatch) Reset() {
	*x = CustomResourceBatch{}
	mi := &file_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResourceBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResourceBatch) ProtoMessage() {}

func (x *CustomResourceBatch) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResourceBatch.ProtoReflect.Descriptor instead.
func (*CustomResourceBatch) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{6}
}

func (x *CustomResourceBatch) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CustomResourceBatch) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *CustomResourceBatch) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *CustomResourceBatch) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CustomResourceBatch) GetResources() []*CustomCollectedResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CustomResourceBatch) GetAggregationValues() map[string]float64 {
	if x != nil {
		return x.AggregationValues
	}
	return nil
}

// CustomCollectedResource is a single collected resource instance.
type CustomCollectedResource struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Labels    map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Values encoded as JSON since they can be any type.
	ValuesJson    []byte `protobuf:"bytes,5,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCollectedResource) Reset() {
	*x = CustomCollectedResource{}
	mi := &file_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCollectedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCollectedResource) ProtoMessage() {}

func (x *CustomCollectedResource) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCollectedResource.ProtoReflect.Descriptor instead.
func (*CustomCollectedResource) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{7}
}

func (x *CustomCollectedResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomCollectedResource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CustomCollectedResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomCollectedResource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CustomCollectedResource) GetValuesJson() []byte {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

// OperatorInfo mirrors pkg/types.OperatorInfo.
type OperatorInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName        string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version            string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InstalledNamespace string                 `protobuf:"bytes,5,opt,name=installed_namespace,json=installedNamespace,proto3" json:"installed_namespace,omitempty"`
	InstallMode        string                 `protobuf:"bytes,6,opt,name=install_mode,json=installMode,proto3" json:"install_mode,omitempty"`
	Provider           string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	IsClusterWide      bool                   `protobuf:"varint,8,opt,name=is_cluster_wide,json=isClusterWide,proto3" json:"is_cluster_wide,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperatorInfo) Reset() {
	*x = OperatorInfo{}
	mi := &file_collector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorInfo) ProtoMessage() {}

func (x *OperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorInfo.ProtoReflect.Descriptor instead.
func (*OperatorInfo) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{8}
}

func (x *OperatorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatorInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OperatorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OperatorInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperatorInfo) GetInstalledNamespace() string {
	if x != nil {
		return x.InstalledNamespace
	}
	return ""
}

func (x *OperatorInfo) GetInstallMode() string {
	if x != nil {
		return x.InstallMode
	}
	return ""
}

func (x *OperatorInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OperatorInfo) GetIsClusterWide() bool {
	if x != nil {
		return x.IsClusterWide
	}
	return false
}

// ClusterOperatorInfo mirrors pkg/types.ClusterOperatorInfo.
type ClusterOperatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Progressing   bool                   `protobuf:"varint,4,opt,name=progressing,proto3" json:"progressing,omitempty"`
	Degraded      bool                   `protobuf:"varint,5,opt,name=degraded,proto3" json:"degraded,omitempty"`
	Upgradeable   bool                   `protobuf:"varint,6,opt,name=upgradeable,proto3" json:"upgradeable,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterOperatorInfo) Reset() {
	*x = ClusterOperatorInfo{}
	mi := &file_collector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOperatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOperatorInfo) ProtoMessage() {}

func (x *ClusterOperatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOperatorInfo.ProtoReflect.Descriptor instead.
func (*ClusterOperatorInfo) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterOperatorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterOperatorInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterOperatorInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ClusterOperatorInfo) GetProgressing() bool {
	if x != nil {
		return x.Progressing
	}
	return false
}

func (x *ClusterOperatorInfo) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *ClusterOperatorInfo) GetUpgradeable() bool {
	if x != nil {
		return x.Upgradeable
	}
	return false
}

func (x *ClusterOperatorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthReport is a periodic heartbeat from the collector.
type HealthReport struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ClusterName              string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Timestamp                *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UptimeSeconds            int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	BufferedBatches          int32                  `protobuf:"varint,4,opt,name=buffered_batches,json=bufferedBatches,proto3" json:"buffered_batches,omitempty"`
	LastCollectionDurationMs int64                  `protobuf:"varint,5,opt,name=last_collection_duration_ms,json=lastCollectionDurationMs,proto3" json:"last_collection_duration_ms,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_collector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{10}
}

func (x *HealthReport) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *HealthReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthReport) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthReport) GetBufferedBatches() int32 {
	if x != nil {
		return x.BufferedBatches
	}
	return 0
}

func (x *HealthReport) GetLastCollectionDurationMs() int64 {
	if x != nil {
		return x.LastCollectionDurationMs
	}
	return 0
}

// ConfigUpdate pushes MetricSource configs to the collector.
type ConfigUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full list of compiled MetricSource configs as JSON.
	// The collector replaces its local config with this set.
	MetricSourcesJson [][]byte `protobuf:"bytes,1,rep,name=metric_sources_json,json=metricSourcesJson,proto3" json:"metric_sources_json,omitempty"`
	// Collection interval override (seconds). 0 = use per-source interval.
	DefaultIntervalSeconds int32 `protobuf:"varint,2,opt,name=default_interval_seconds,json=defaultIntervalSeconds,proto3" json:"default_interval_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_collector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigUpdate) GetMetricSourcesJson() [][]byte {
	if x != nil {
		return x.MetricSourcesJson
	}
	return nil
}

func (x *ConfigUpdate) GetDefaultIntervalSeconds() int32 {
	if x != nil {
		return x.DefaultIntervalSeconds
	}
	return 0
}

// Ack acknowledges receipt of a MetricsBatch.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_collector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_collector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_collector_proto_rawDescGZIP(), []int{12}
}

func (x *Ack) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_collector_proto protoreflect.FileDescriptor

const file_collector_proto_rawDesc = "" +
	"\n" +
	"\x0fcollector.proto\x12\x19clusterpulse.collector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\x10CollectorMessage\x12C\n" +
	"\ametrics\x18\x01 \x01(\v2'.clusterpulse.collector.v1.MetricsBatchH\x00R\ametrics\x12A\n" +
	"\x06health\x18\x02 \x01(\v2'.clusterpulse.collector.v1.HealthReportH\x00R\x06health\x12H\n" +
	"\bregister\x18\x03 \x01(\v2*.clusterpulse.collector.v1.RegisterRequestH\x00R\bregisterB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\x0fIngesterMessage\x12A\n" +
	"\x06config\x18\x01 \x01(\v2'.clusterpulse.collector.v1.ConfigUpdateH\x00R\x06config\x122\n" +
	"\x03ack\x18\x02 \x01(\v2\x1e.clusterpulse.collector.v1.AckH\x00R\x03ackB\t\n" +
	"\apayload\"d\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xa9\x04\n" +
	"\fMetricsBatch\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12R\n" +
	"\x0fcluster_metrics\x18\x04 \x01(\v2).clusterpulse.collector.v1.ClusterMetricsR\x0eclusterMetrics\x12I\n" +
	"\fnode_metrics\x18\x05 \x03(\v2&.clusterpulse.collector.v1.NodeMetricsR\vnodeMetrics\x12Y\n" +
	"\x10custom_resources\x18\x06 \x03(\v2..clusterpulse.collector.v1.CustomResourceBatchR\x0fcustomResources\x12E\n" +
	"\toperators\x18\a \x03(\v2'.clusterpulse.collector.v1.OperatorInfoR\toperators\x12[\n" +
	"\x11cluster_operators\x18\b \x03(\v2..clusterpulse.collector.v1.ClusterOperatorInfoR\x10clusterOperators\"\xf2\x04\n" +
	"\x0eClusterMetrics\x12\x14\n" +
	"\x05nodes\x18\x01 \x01(\x05R\x05nodes\x12\x1f\n" +
	"\vnodes_ready\x18\x02 \x01(\x05R\n" +
	"nodesReady\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x01(\x05R\n" +
	"namespaces\x12%\n" +
	"\x0enamespace_list\x18\x05 \x03(\tR\rnamespaceList\x12\x12\n" +
	"\x04pods\x18\x06 \x01(\x05R\x04pods\x12!\n" +
	"\fpods_running\x18\a \x01(\x05R\vpodsRunning\x12!\n" +
	"\fcpu_capacity\x18\n" +
	" \x01(\x01R\vcpuCapacity\x12'\n" +
	"\x0fmemory_capacity\x18\x0e \x01(\x03R\x0ememoryCapacity\x12 \n" +
	"\vdeployments\x18\x16 \x01(\x05R\vdeploymentsJ\x04\b\x03\x10\x04J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"J\x04\b\v\x10\fJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11J\x04\b\x11\x10\x12J\x04\b\x12\x10\x13J\x04\b\x13\x10\x14J\x04\b\x14\x10\x15J\x04\b\x15\x10\x16J\x04\b\x17\x10\x18J\x04\b\x18\x10\x19R\x0fnodes_not_readyR\fpods_pendingR\vpods_failedR\x0fcpu_allocatableR\rcpu_requestedR\x11cpu_usage_percentR\x12memory_allocatableR\x10memory_requestedR\x14memory_usage_percentR\x10storage_capacityR\fstorage_usedR\x04pvcsR\bservicesR\fstatefulsetsR\n" +
	"daemonsets\"\xfa\b\n" +
	"\vNodeMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12!\n" +
	"\fcpu_capacity\x18\n" +
	" \x01(\x01R\vcpuCapacity\x12'\n" +
	"\x0fmemory_capacity\x18\v \x01(\x03R\x0ememoryCapacity\x12)\n" +
	"\x10storage_capacity\x18\f \x01(\x03R\x0fstorageCapacity\x12#\n" +
	"\rpods_capacity\x18\r \x01(\x05R\fpodsCapacity\x12'\n" +
	"\x0fcpu_allocatable\x18\x0e \x01(\x01R\x0ecpuAllocatable\x12-\n" +
	"\x12memory_allocatable\x18\x0f \x01(\x03R\x11memoryAllocatable\x12/\n" +
	"\x13storage_allocatable\x18\x10 \x01(\x03R\x12storageAllocatable\x12)\n" +
	"\x10pods_allocatable\x18\x11 \x01(\x05R\x0fpodsAllocatable\x12#\n" +
	"\rcpu_requested\x18\x12 \x01(\x01R\fcpuRequested\x12)\n" +
	"\x10memory_requested\x18\x13 \x01(\x03R\x0fmemoryRequested\x12*\n" +
	"\x11cpu_usage_percent\x18\x14 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x15 \x01(\x01R\x12memoryUsagePercent\x12!\n" +
	"\fpods_running\x18\x16 \x01(\x05R\vpodsRunning\x12!\n" +
	"\fpods_pending\x18\x17 \x01(\x05R\vpodsPending\x12\x1f\n" +
	"\vpods_failed\x18\x18 \x01(\x05R\n" +
	"podsFailed\x12%\n" +
	"\x0epods_succeeded\x18\x19 \x01(\x05R\rpodsSucceeded\x12\x1d\n" +
	"\n" +
	"pods_total\x18\x1a \x01(\x05R\tpodsTotal\x12%\n" +
	"\x0ekernel_version\x18\x1e \x01(\tR\rkernelVersion\x12\x19\n" +
	"\bos_image\x18\x1f \x01(\tR\aosImage\x12+\n" +
	"\x11container_runtime\x18  \x01(\tR\x10containerRuntime\x12'\n" +
	"\x0fkubelet_version\x18! \x01(\tR\x0ekubeletVersion\x12\"\n" +
	"\farchitecture\x18\" \x01(\tR\farchitecture\x12J\n" +
	"\x06labels\x18# \x03(\v22.clusterpulse.collector.v1.NodeMetrics.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vinternal_ip\x18$ \x01(\tR\n" +
	"internalIp\x12\x1a\n" +
	"\bhostname\x18% \x01(\tR\bhostname\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x03\n" +
	"\x13CustomResourceBatch\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12%\n" +
	"\x0eresource_count\x18\x02 \x01(\x05R\rresourceCount\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12P\n" +
	"\tresources\x18\x05 \x03(\v22.clusterpulse.collector.v1.CustomCollectedResourceR\tresources\x12t\n" +
	"\x12aggregation_values\x18\x06 \x03(\v2E.clusterpulse.collector.v1.CustomResourceBatch.AggregationValuesEntryR\x11aggregationValues\x1aD\n" +
	"\x16AggregationValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x8f\x02\n" +
	"\x17CustomCollectedResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12V\n" +
	"\x06labels\x18\x04 \x03(\v2>.clusterpulse.collector.v1.CustomCollectedResource.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vvalues_json\x18\x05 \x01(\fR\n" +
	"valuesJson\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\fOperatorInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x13installed_namespace\x18\x05 \x01(\tR\x12installedNamespace\x12!\n" +
	"\finstall_mode\x18\x06 \x01(\tR\vinstallMode\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12&\n" +
	"\x0fis_cluster_wide\x18\b \x01(\bR\risClusterWide\"\xdb\x01\n" +
	"\x13ClusterOperatorInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12 \n" +
	"\vprogressing\x18\x04 \x01(\bR\vprogressing\x12\x1a\n" +
	"\bdegraded\x18\x05 \x01(\bR\bdegraded\x12 \n" +
	"\vupgradeable\x18\x06 \x01(\bR\vupgradeable\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xfc\x01\n" +
	"\fHealthReport\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12)\n" +
	"\x10buffered_batches\x18\x04 \x01(\x05R\x0fbufferedBatches\x12=\n" +
	"\x1blast_collection_duration_ms\x18\x05 \x01(\x03R\x18lastCollectionDurationMs\"x\n" +
	"\fConfigUpdate\x12.\n" +
	"\x13metric_sources_json\x18\x01 \x03(\fR\x11metricSourcesJson\x128\n" +
	"\x18default_interval_seconds\x18\x02 \x01(\x05R\x16defaultIntervalSeconds\"P\n" +
	"\x03Ack\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2z\n" +
	"\x10CollectorService\x12f\n" +
	"\aConnect\x12+.clusterpulse.collector.v1.CollectorMessage\x1a*.clusterpulse.collector.v1.IngesterMessage(\x010\x01B>Z<github.com/clusterpulse/cluster-controller/proto/collectorpbb\x06proto3"

var (
	file_collector_proto_rawDescOnce sync.Once
	file_collector_proto_rawDescData []byte
)

func file_collector_proto_rawDescGZIP() []byte {
	file_collector_proto_rawDescOnce.Do(func() {
		file_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)))
	})
	return file_collector_proto_rawDescData
}

var file_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_collector_proto_goTypes = []any{
	(*CollectorMessage)(nil),        // 0: clusterpulse.collector.v1.CollectorMessage
	(*IngesterMessage)(nil),         // 1: clusterpulse.collector.v1.IngesterMessage
	(*RegisterRequest)(nil),         // 2: clusterpulse.collector.v1.RegisterRequest
	(*MetricsBatch)(nil),            // 3: clusterpulse.collector.v1.MetricsBatch
	(*ClusterMetrics)(nil),          // 4: clusterpulse.collector.v1.ClusterMetrics
	(*NodeMetrics)(nil),             // 5: clusterpulse.collector.v1.NodeMetrics
	(*CustomResourceBatch)(nil),     // 6: clusterpulse.collector.v1.CustomResourceBatch
	(*CustomCollectedResource)(nil), // 7: clusterpulse.collector.v1.CustomCollectedResource
	(*OperatorInfo)(nil),            // 8: clusterpulse.collector.v1.OperatorInfo
	(*ClusterOperatorInfo)(nil),     // 9: clusterpulse.collector.v1.ClusterOperatorInfo
	(*HealthReport)(nil),            // 10: clusterpulse.collector.v1.HealthReport
	(*ConfigUpdate)(nil),            // 11: clusterpulse.collector.v1.ConfigUpdate
	(*Ack)(nil),                     // 12: clusterpulse.collector.v1.Ack
	nil,                             // 13: clusterpulse.collector.v1.NodeMetrics.LabelsEntry
	nil,                             // 14: clusterpulse.collector.v1.CustomResourceBatch.AggregationValuesEntry
	nil,                             // 15: clusterpulse.collector.v1.CustomCollectedResource.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
}
var file_collector_proto_depIdxs = []int32{
	3,  // 0: clusterpulse.collector.v1.CollectorMessage.metrics:type_name -> clusterpulse.collector.v1.MetricsBatch
	10, // 1: clusterpulse.collector.v1.CollectorMessage.health:type_name -> clusterpulse.collector.v1.HealthReport
	2,  // 2: clusterpulse.collector.v1.CollectorMessage.register:type_name -> clusterpulse.collector.v1.RegisterRequest
	11, // 3: clusterpulse.collector.v1.IngesterMessage.config:type_name -> clusterpulse.collector.v1.ConfigUpdate
	12, // 4: clusterpulse.collector.v1.IngesterMessage.ack:type_name -> clusterpulse.collector.v1.Ack
	16, // 5: clusterpulse.collector.v1.MetricsBatch.collected_at:type_name -> google.protobuf.Timestamp
	4,  // 6: clusterpulse.collector.v1.MetricsBatch.cluster_metrics:type_name -> clusterpulse.collector.v1.ClusterMetrics
	5,  // 7: clusterpulse.collector.v1.MetricsBatch.node_metrics:type_name -> clusterpulse.collector.v1.NodeMetrics
	6,  // 8: clusterpulse.collector.v1.MetricsBatch.custom_resources:type_name -> clusterpulse.collector.v1.CustomResourceBatch
	8,  // 9: clusterpulse.collector.v1.MetricsBatch.operators:type_name -> clusterpulse.collector.v1.OperatorInfo
	9,  // 10: clusterpulse.collector.v1.MetricsBatch.cluster_operators:type_name -> clusterpulse.collector.v1.ClusterOperatorInfo
	13, // 11: clusterpulse.collector.v1.NodeMetrics.labels:type_name -> clusterpulse.collector.v1.NodeMetrics.LabelsEntry
	7,  // 12: clusterpulse.collector.v1.CustomResourceBatch.resources:type_name -> clusterpulse.collector.v1.CustomCollectedResource
	14, // 13: clusterpulse.collector.v1.CustomResourceBatch.aggregation_values:type_name -> clusterpulse.collector.v1.CustomResourceBatch.AggregationValuesEntry
	15, // 14: clusterpulse.collector.v1.CustomCollectedResource.labels:type_name -> clusterpulse.collector.v1.CustomCollectedResource.LabelsEntry
	16, // 15: clusterpulse.collector.v1.HealthReport.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 16: clusterpulse.collector.v1.CollectorService.Connect:input_type -> clusterpulse.collector.v1.CollectorMessage
	1,  // 17: clusterpulse.collector.v1.CollectorService.Connect:output_type -> clusterpulse.collector.v1.IngesterMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_collector_proto_init() }
func file_collector_proto_init() {
	if File_collector_proto != nil {
		return
	}
	file_collector_proto_msgTypes[0].OneofWrappers = []any{
		(*CollectorMessage_Metrics)(nil),
		(*CollectorMessage_Health)(nil),
		(*CollectorMessage_Register)(nil),
	}
	file_collector_proto_msgTypes[1].OneofWrappers = []any{
		(*IngesterMessage_Config)(nil),
		(*IngesterMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collector_proto_rawDesc), len(file_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_proto_goTypes,
		DependencyIndexes: file_collector_proto_depIdxs,
		MessageInfos:      file_collector_proto_msgTypes,
	}.Build()
	File_collector_proto = out.File
	file_collector_proto_goTypes = nil
	file_collector_proto_depIdxs = nil
}
